public enum NetworkCommand: uint {
	MOVE_COMMAND = 0,
	SHOOT_COMMAND = 1,
	JOIN_COMMAND = 2,
	JOIN_RESPONSE_COMMAND = 3,
	JOIN_PLAYER_COMMAND = 4,
	PROJECTILE_SHOOT_COMMAND = 5,
	DISCONNECT_COMMAND = 6,
	PROJECTILE_EXPLODE_COMMAND = 7,
}

